[2025-09-10T05:49:46.934+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: realtime_pipeline.spark_job scheduled__2025-09-09T00:00:00+00:00 [queued]>
[2025-09-10T05:49:46.956+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: realtime_pipeline.spark_job scheduled__2025-09-09T00:00:00+00:00 [queued]>
[2025-09-10T05:49:46.957+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-09-10T05:49:46.991+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): spark_job> on 2025-09-09 00:00:00+00:00
[2025-09-10T05:49:47.001+0000] {standard_task_runner.py:57} INFO - Started process 470 to run task
[2025-09-10T05:49:47.012+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'realtime_pipeline', 'spark_job', 'scheduled__2025-09-09T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/realtime_pipeline.py', '--cfg-path', '/tmp/tmpopiamako']
[2025-09-10T05:49:47.030+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask spark_job
[2025-09-10T05:49:47.157+0000] {task_command.py:416} INFO - Running <TaskInstance: realtime_pipeline.spark_job scheduled__2025-09-09T00:00:00+00:00 [running]> on host 2e60c95814dd
[2025-09-10T05:49:47.306+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='realtime_pipeline' AIRFLOW_CTX_TASK_ID='spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-09-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-09T00:00:00+00:00'
[2025-09-10T05:49:47.311+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-10T05:49:47.315+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec spark-master /opt/bitnami/spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.postgresql:postgresql:42.5.1 /opt/bitnami/spark/apps/spark_streaming.py']
[2025-09-10T05:49:47.341+0000] {subprocess.py:86} INFO - Output:
[2025-09-10T05:49:48.013+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2025-09-10T05:49:48.023+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-10T05:49:48.138+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-10T05:49:48.189+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=realtime_pipeline, task_id=spark_job, execution_date=20250909T000000, start_date=20250910T054946, end_date=20250910T054948
[2025-09-10T05:49:48.225+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task spark_job (Bash command failed. The command returned a non-zero exit code 1.; 470)
[2025-09-10T05:49:48.267+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-10T05:49:48.317+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
