[2025-09-09T18:48:21.794+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: realtime_pipeline.spark_job manual__2025-09-09T18:48:18.620446+00:00 [queued]>
[2025-09-09T18:48:21.803+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: realtime_pipeline.spark_job manual__2025-09-09T18:48:18.620446+00:00 [queued]>
[2025-09-09T18:48:21.804+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-09-09T18:48:21.823+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): spark_job> on 2025-09-09 18:48:18.620446+00:00
[2025-09-09T18:48:21.831+0000] {standard_task_runner.py:57} INFO - Started process 256 to run task
[2025-09-09T18:48:21.835+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'realtime_pipeline', 'spark_job', 'manual__2025-09-09T18:48:18.620446+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/realtime_pipeline.py', '--cfg-path', '/tmp/tmps37qsvgd']
[2025-09-09T18:48:21.838+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask spark_job
[2025-09-09T18:48:21.924+0000] {task_command.py:416} INFO - Running <TaskInstance: realtime_pipeline.spark_job manual__2025-09-09T18:48:18.620446+00:00 [running]> on host 54b33d5810b5
[2025-09-09T18:48:22.029+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='realtime_pipeline' AIRFLOW_CTX_TASK_ID='spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-09-09T18:48:18.620446+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-09T18:48:18.620446+00:00'
[2025-09-09T18:48:22.031+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-09T18:48:22.032+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec spark-master /opt/bitnami/spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.postgresql:postgresql:42.5.1 /opt/bitnami/spark/apps/spark_streaming.py']
[2025-09-09T18:48:22.044+0000] {subprocess.py:86} INFO - Output:
[2025-09-09T18:48:22.234+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2025-09-09T18:48:22.236+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-09T18:48:22.290+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-09T18:48:22.295+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=realtime_pipeline, task_id=spark_job, execution_date=20250909T184818, start_date=20250909T184821, end_date=20250909T184822
[2025-09-09T18:48:22.323+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task spark_job (Bash command failed. The command returned a non-zero exit code 1.; 256)
[2025-09-09T18:48:22.371+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-09T18:48:22.393+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
